#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed Jul 26 00:57:45 2017

@author: jzhng105
"""
from selenium import webdriver
import pandas as pd

url = "https://www.sedi.ca/sedi/SVTSelectSediInsider?menukey=15.01.00&locale=en_CA"
number1 = "ABALAZS001"
number2 = "00003819"
def lookupinfo(number):
    data = []
    #driver = webdriver.Chrome(executable_path="/usr/local/chromedriver") 
    driver.get(url)
    element_ID = driver.find_element_by_name('INSIDER_KEY')
    element_ID.send_keys(number)
    element_Search = driver.find_element_by_name('Search')
    element_Search.click()
    element_Select = driver.find_element_by_name('UID_INSPR')
    element_Select.click()
    element_Next = driver.find_element_by_name('Next')
    element_Next.click()
    for td in driver.find_elements_by_css_selector("td[valign$=top]"):
        info = td.text.replace("\n", "*")
        info = info.split("*")
        info = list(filter(None, info))
        data.append(info)
        data = [x for x in data if x != []]
    return(data[3])

def lookupinsiderID(issuernumber):
    ID = []
    finalID = []
    driver.get(url)
    element_ID = driver.find_element_by_name('ISSH_NIPDB')
    element_ID.send_keys(issuernumber)
    element_Search = driver.find_element_by_name('Search')
    element_Search.click()
    for td in driver.find_elements_by_css_selector("td[valign$=top]"):
        issuerID = td.text.replace("\n", "*")
        issuerID = issuerID.split("*")
        issuerID = list(filter(None, issuerID))
        if len(str(issuerID).split()) == 1 :
            ID.append(list(issuerID))
        ID = [x for x in ID if x != []]
    for i in range(0,len(ID)):
        if any(char.isdigit() for char in str(ID[i])):
             ID[i] = "".join(y for y in ID[i] if y not in "()'")
             finalID.append(ID[i])
    print(finalID)
    print(len(finalID))
    return(finalID)

issuer_ID = []        
driver = webdriver.Chrome(executable_path="/usr/local/chromedriver") 
issuer_ID.append(lookupinsiderID(number2))  
df = pd.DataFrame(issuer_ID)
df.to_csv("issuer_ID.csv")

insider_info = []
driver = webdriver.Chrome(executable_path="/usr/local/chromedriver") 
insider_info.append(lookupinfo(number1))
df = pd.DataFrame(insider_info)
df.to_csv("Insiderinfo.csv")

#for i in range(10000):
#    number = '{0:08}'.format(i)
#    try:
#        insider_info.append(lookupinfo(number))
#    except:
#        continue

#for i in range(0:len(insider_info)):
#    try:
#        insider_info.append(lookupinfo(insider_info[i]))
#    except:
#        continue


    
    
    

#for table in soup.find_all("table", attrs={"width":"100%"}):
#    td = table.find('td')
#    data.append(td.renderContents())
#print(data)
#for table in bs.findALL('td'):
#    data.append(table.renderContents())
#print(table)
#except:
#    continue


